// This file is generated by npm run icons

export type IconName =
	| "archive"
	| "bolt"
	| "calendar"
	| "check"
	| "chervronDown"
	| "chevron-left"
	| "chevron-right"
	| "chevron-up"
	| "close"
	| "edit"
	| "external-link"
	| "mail"
	| "medical"
	| "plus"
	| "salary"
	| "slash"
	| "trash"
	| "view";
